---

- name: get ticket from master
  uri:
    url: '{{ icinga2_client_api_url }}/v1/actions/generate-ticket'
    method: POST
    user: '{{ icinga2_client_api_user }}'
    password: '{{ icinga2_client_api_pass }}'
    body: '{ "cn": "{{ inventory_hostname }}"}'
    force_basic_auth: yes
    status_code: 200
    body_format: 'json'
    headers:
      Accept: 'application/json'
    validate_certs : no
  register: icinga2_client_ticket

# - name: generate ticket on master
#   shell: "icinga2 pki ticket --cn {{ inventory_hostname }} --salt {{ icinga2_salt }}"
#   register: icinga2_client_ticket
#   delegate_to: "{{ icinga2_master_fqdn }}"

- name: Ticket generated!
  debug:
    msg: "{{ icinga2_client_ticket }}"

- name: Ticket and fqdn
  debug:
    msg: "{{ icinga2_client_ticket }} : is for {{ inventory_hostname }}"

# - name: create pki folder on clients
#   file:
#     dest: /etc/icinga2/pki
#     state: directory
#     mode: 0700
#     owner: icinga
#     group: icinga
#
# - name: create cert
#   shell: |
#     {{ icinga2_binary }} pki new-cert \
#     --cn {{ inventory_hostname }} \
#     --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
#     --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
#
# - name: save the masters cert as trustedcert
#   shell: |
#     {{ icinga2_binary }} pki save-cert \
#     --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
#     --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
#     --trustedcert /etc/icinga2/pki/trusted-master.crt \
#     --host {{ icinga2_master_fqdn }}
#
# - name: request the certificate from the icinga server
#   shell: |
#     {{ icinga2_binary }} pki request \
#     --host {{ icinga2_master_fqdn }} \
#     --port {{ icinga2_api_port }} \
#     --ticket {{ icinga2_client_ticket['stdout'] }} \
#     --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
#     --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
#     --trustedcert /etc/icinga2/pki/trusted-master.crt --ca /etc/icinga2/pki/ca.key
#
#     #- name: node setup
#     #  shell: |
#     #    {{ icinga2_binary }} node setup \
#     #    --ticket {{ icinga2_client_ticket['stdout'] }} \
#     #    --endpoint {{ icinga2_master_fqdn }} \
#     #    --zone {{ inventory_hostname }} \
#     #    --master_host {{ icinga2_master_fqdn }} \
#     #    --trustedcert /etc/icinga2/pki/trusted-master.crt \
#     #    --cn {{ inventory_hostname }} \
#     #    --accept-commands \
#     #    --accept-config
#
# - name: get certificate fingerprint
#   shell: |
#     openssl x509 \
#     -in /etc/icinga2/pki/{{ inventory_hostname }}.crt \
#     -fingerprint -sha256 -noout | cut -d '=' -f 2 | sed 's/://g' | tr A-Z a-z
#   register: icinga2_fingerprint
#
# - name: sign certificate request on master
#   shell: |
#     {{ icinga2_binary }} ca sign {{ icinga2_fingerprint['stdout'] }}
#   delegate_to: "{{ icinga2_master_fqdn }}"
